import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "react-hot-toast";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        variables: {
          colorText: "white",
          colorPrimary: "#0E78F9",
          colorBackground: "#1C1F2E",
          colorInputBackground: "#252A41",
          colorInputText: "white",
        },
        elements: {
          userButtonPopoverActionButton:
            "hover:bg-[#252A41] hover:text-white text-white",
          userButtonPopoverUserName: "text-white",
          userButtonPopoverUserIdentifier: "text-white",
          userButtonPopoverFooter: "text-white",
          userButtonPopover: "text-white",
        },
      }}
    >
      <html lang="en">
        <body
          className={`${geistSans.variable} bg-dark-2 ${geistMono.variable} text-white antialiased`}
        >
          <Toaster />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
